# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms 
# will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do 
# not exceed four million, find the sum of the even-valued terms.

range = 4000000

fibonacci = []
even = []

def evenfib(n):
    fibonacci = []
    even = []
    a, b = 0, 1
    while b < n:
        fibonacci.append(b)
        if (b%2 == 0):
            even.append(b)
        a, b = b, a+b
    return even

print(sum(evenfib(range)))
